import { EcsBounceAppPartModule } from "./parts/ecs-bounce.ts";
import { MatrixAppPartModule } from "./parts/matrix.ts";
import { MeshNextAppPartModule } from "./parts/mesh-next.ts";
import { PathAreaAppPartModule } from "./parts/path-area.ts";
import { PathClipAppPartModule } from "./parts/path-clip.ts";
import { PathIntersectionAppPartModule } from "./parts/path-intersection.ts";
import { PathOperationAppPartModule } from "./parts/path-operations.ts";
import { PathOverlayAppPartModule } from "./parts/path-overlay.ts";
import { PlaygroundAppPartModule } from "./parts/playground.ts";
import { PolygonMinkowskiAppPartModule } from "./parts/polygon-minkowski.ts";
import { SamplingAppPartModule } from "./parts/sampling.ts";
import { SnapRoundingAppPartModule } from "./parts/snap-rounding.ts";
import { StraightSkeletonAppPartModule } from "./parts/straight-skeleton.ts";
import { TriangulateAppPartModule } from "./parts/triangulate.ts";
import { AppLauncher } from "./utility/app-launcher.ts";

const launcher = new AppLauncher();
launcher.addPart("ecs-bounce", new EcsBounceAppPartModule());
launcher.addPart("matrix", new MatrixAppPartModule());
launcher.addPart("mesh", new MeshNextAppPartModule());
launcher.addPart("mesh-next", new MeshNextAppPartModule());
launcher.addPart("path-area", new PathAreaAppPartModule());
launcher.addPart("path-clip", new PathClipAppPartModule());
launcher.addPart("path-intersection", new PathIntersectionAppPartModule());
launcher.addPart("path-operations", new PathOperationAppPartModule());
launcher.addPart("path-overlay", new PathOverlayAppPartModule());
launcher.addPart("playground", new PlaygroundAppPartModule());
launcher.addPart("polygon-minkowski", new PolygonMinkowskiAppPartModule());
launcher.addPart("sampling", new SamplingAppPartModule());
launcher.addPart("snap-rounding", new SnapRoundingAppPartModule());
launcher.addPart("straight-skeleton", new StraightSkeletonAppPartModule());
launcher.addPart("triangulate", new TriangulateAppPartModule());

await launcher.run("ecs-bounce");
