import { ECS_MAIN_WORLD } from "./parts/ecs-bounce.ts";
import { MATRIX_MAIN_WORLD } from "./parts/matrix.ts";
import { MESH_NEXT_MAIN_WORLD } from "./parts/mesh-next.ts";
import { MESH_MAIN_WORLD } from "./parts/mesh.ts";
import { PATH_AREA_MAIN_WORLD } from "./parts/path-area.ts";
import { PATH_CLIP_MAIN_WORLD } from "./parts/path-clip.ts";
import { PATH_INTERSECTION_MAIN_WORLD } from "./parts/path-intersection.ts";
import { PATH_OPERATIONS_MAIN_WORLD } from "./parts/path-operations.ts";
import { PATH_OVERLAY_MAIN_WORLD } from "./parts/path-overlay.ts";
import { PLAYGROUND_MAIN_WORLD } from "./parts/playground.ts";
import { POLYGON_MINKOWSKI_MAIN_WORLD } from "./parts/polygon-minkowski.ts";
import { SAMPLING_MAIN_WORLD } from "./parts/sampling.ts";
import { SNAP_ROUNDING_MAIN_WORLD } from "./parts/snap-rounding.ts";
import { STRAIGHT_SKELETON_MAIN_WORLD } from "./parts/straight-skeleton.ts";
import { TRIANGULATE_MAIN_WORLD } from "./parts/triangulate.ts";
import { AppLauncher } from "./utility/app-launcher.ts";

const launcher = new AppLauncher();
launcher.addPart("ecs-bounce", ECS_MAIN_WORLD);
launcher.addPart("matrix", MATRIX_MAIN_WORLD);
launcher.addPart("mesh", MESH_MAIN_WORLD);
launcher.addPart("mesh-next", MESH_NEXT_MAIN_WORLD);
launcher.addPart("path-area", PATH_AREA_MAIN_WORLD);
launcher.addPart("path-clip", PATH_CLIP_MAIN_WORLD);
launcher.addPart("path-intersection", PATH_INTERSECTION_MAIN_WORLD);
launcher.addPart("path-operations", PATH_OPERATIONS_MAIN_WORLD);
launcher.addPart("path-overlay", PATH_OVERLAY_MAIN_WORLD);
launcher.addPart("polygon-minkowski", POLYGON_MINKOWSKI_MAIN_WORLD);
launcher.addPart("playground", PLAYGROUND_MAIN_WORLD);
launcher.addPart("sampling", SAMPLING_MAIN_WORLD);
launcher.addPart("snap-rounding", SNAP_ROUNDING_MAIN_WORLD);
launcher.addPart("straight-skeleton", STRAIGHT_SKELETON_MAIN_WORLD);
launcher.addPart("triangulate", TRIANGULATE_MAIN_WORLD);
launcher.run("ecs-bounce");
