name: Deploy to gh-pages
on:
    push:
        branches:
            - release
jobs:
    deploy-gh-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install
              run: pnpm install --frozen-lockfile
            - name: Build
              run: |
                  pnpm run check
                  pnpm run lint
                  pnpm run test
                  pnpm run build -w redgeometry-app
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: packages/redgeometry-app/dist
