name: Publish to npm
on:
    push:
        branches:
            - release
jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install
              run: npm ci
            - name: Check, Lint & Test
              run: |
                  npm run check
                  npm run lint
                  npm run test
            - name: Build
              run: npm run build -w redgeometry
            - name: Publish
              run: npm publish ./packages/redgeometry
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
