name: Publish to npm
on:
    push:
        branches:
            - release
jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: "https://registry.npmjs.org"
            - name: Install
              run: pnpm install --frozen-lockfile
            - name: Build
              run: |
                  pnpm run check
                  pnpm run lint
                  pnpm run test
                  pnpm run build -w redgeometry
            - name: Publish
              run: pnpm publish ./packages/redgeometry
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
